apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  name: v1beta1.custom.metrics.k8s.io
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: {{ include "katalyst-metric.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1beta1
  versionPriority: 100

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  name: v1beta1.external.metrics.k8s.io
spec:
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: {{ include "katalyst-metric.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1beta1
  versionPriority: 100