{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  name: {{ include "katalyst-metric.serviceAccountName" . }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  name: {{ include "katalyst-metric.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "katalyst-metric.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "katalyst-metric.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  name: {{ include "katalyst-metric.serviceAccountName" . }}:system:auth-reader
  namespace: "kube-system"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "katalyst-metric.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  name: {{ include "katalyst-metric.serviceAccountName" . }}:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ include "katalyst-metric.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "katalyst-metric.serviceAccountName" . }}
  labels:
    {{- include "katalyst-metric.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: katalyst-metric-view
rules:
  - apiGroups:
      - "custom.metrics.k8s.io"
    resources:
      - "*"
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - "external.metrics.k8s.io"
    resources:
      - "*"
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: katalyst-metric-view-binding
subjects:
  - kind: User
    name: kubernetes
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: katalyst-metric-view