apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "malachite.fullname" . }}
  labels:
    {{- include "malachite.labels" . | nindent 4 }}
    app: "malachite"
spec:
  selector:
    matchLabels:
      {{- include "malachite.selectorLabels" . | nindent 6 }}
      app: "malachite"
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "malachite.selectorLabels" . | nindent 8 }}
        app: "malachite"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - {{ default "malachite" .Values.customCommand }}
          env:
            - name: ROCKET_CONFIG
              value: "/etc/malachite/bin/static/Rocket.toml"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy }}
          workingDir: /etc/malachite
          ports:
            - name: healthz
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /sys
              name: host-sys-dir
              readOnly: true
            - mountPath: /tmp
              name: host-tmp-dir
            - mountPath: /sys/fs/cgroup
              name: cgroups
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      restartPolicy: Always
      hostNetwork: true
      volumes:
        - hostPath:
            path: /sys/fs/cgroup
            type: ""
          name: cgroups
        - hostPath:
            path: /sys
            type: ""
          name: host-sys-dir
        - hostPath:
            path: /tmp
            type: ""
          name: host-tmp-dir
