apiVersion: v1
data:
  tls.crt: {{ .Files.Get "keys/tls.crt" }}
  tls.key: {{ .Files.Get "keys/tls.key" }}
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "katalyst-webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls