apiVersion: v1
kind: Service
metadata:
  name: {{ include "katalyst-webhook.fullname" . }}
  labels:
    {{- include "katalyst-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: secure-port
      protocol: TCP
      name: webhook
  selector:
    {{- include "katalyst-webhook.selectorLabels" . | nindent 4 }}
