image:
  registry: docker.io
  repository: kubewharf/malachite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  "katalyst.kubewharf.io/qos_level": system_cores

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

customCommand: {}
