# Overrides katalyst-webhook values
katalyst-webhook:
  enabled: true

  fullnameOverride: katalyst-webhook

  replicaCount: 1

  image:
    registry: docker.io
    repository: kubewharf/katalyst-webhook
    pullPolicy: IfNotPresent
    tag: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9316"

  customArgs:
    webhooks: "node,lifecycle,-vpa,-pod"

# Overrides katalyst-controller values
katalyst-controller:
  enabled: true

  fullnameOverride: katalyst-controller

  replicaCount: 1

  image:
    registry: docker.io
    repository: kubewharf/katalyst-controller
    pullPolicy: IfNotPresent
    tag: ""

  customArgs:
    controllers: "overcommit,-vpa,-kcc,-spd,-lifecycle"
    dry-run: false
    leader-elect: true
    healthz-enabled: true
    v: 2
    cnc-lifecycle-enabled: false


# Overrides katalyst-agent values
katalyst-agent:
  enabled: true

  image:
    registry: docker.io
    repository: kubewharf/katalyst-agent
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: { }
    name: katalyst-agent

  podAnnotations:
    "katalyst.kubewharf.io/qos_level": system_cores

  resources: { }

  nodeSelector: { }

  tolerations:
    - effect: NoSchedule
      operator: Exists

  affinity: { }

  customCommand: { }

  customArgs:
    agents: "katalyst-agent-reporter,katalyst-agent-advisor"
    sysadvisor-plugins: "overcommit_aware"
    realtime-overcommit-sync-period: "10s"
    realtime-overcommit-CPU-targetload: 0.6
    realtime-overcommit-mem-targetload: 0.6
    realtime-overcommit-estimated-cpuload: 0.4
    realtime-overcommit-estimated-memload: 0.6
    CPU-metrics-to-gather: "cpu.usage.container"
    memory-metrics-to-gather: "mem.rss.container"
    enable-kubelet-secure-port: true

  hostMountPaths:
    kubeletLibDir: /var/lib/kubelet
    runtimeSocketDir: /run/containerd
    katalystLibDir: /var/lib/katalyst


# Overrides katalyst-scheduler values
katalyst-scheduler:
  enabled: true

  replicaCount: 2

  image:
    registry: docker.io
    repository: kubewharf/katalyst-scheduler
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: { }
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: katalyst-scheduler

  podAnnotations: { }

  resources: { }

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }

  customCommand: { }

  customArgs: { }

  leaderElection:
    leaderElect: true

  schedulerPolicy:
    scoringStrategy:
      type: LeastAllocated

  schedulerName: katalyst-scheduler
