
global:
  image: {}

image:
  registry: docker.io
  repository: kubewharf/katalyst-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  name: katalyst-agent

podAnnotations:
  "katalyst.kubewharf.io/qos_level": system_cores

resources: {}

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    operator: Exists

affinity: {}

customCommand: {}

customArgs:
  agents: "*"
  eviction-plugins: "*"
  enable-reclaim: true
  cpu-resource-plugin-advisor: true
  enable-cpu-pressure-eviction: true

hostMountPaths:
  kubeletLibDir: /var/lib/kubelet
  runtimeSocketDir: /run/containerd
  katalystLibDir: /var/lib/katalyst

